build: false

platform: x64

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.1"
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda36-x64

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy matplotlib pytest pytest-cov pandas"
  - activate test-environment
  - pip install coverage tensorflow
  - python setup.py install

test_script:
  - mkdir for_test
  - cd for_test
  - py.test --pyargs battdeg --cov-report term-missing --cov=battdeg
